### ISSUE TITLE
pparent recursion within a with_prototype action: 25000 context sanity limit hit

### ISSUE THREAD

**Issue by sshadmand** [borela/naomi#187] opened 2018-11-04 18:22 UTC
Just installed the package and imedietly got this error.

Sublime 3 

```
Error loading syntax file "Packages/Markdown/Markdown.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit
```

<img width="869" alt="screen shot 2018-11-04 at 10 22 02 am" src="https://user-images.githubusercontent.com/68735/47968210-7e26a200-e01b-11e8-93dc-987e24d6ceae.png">

**Comment by borela** [comment] 2018-11-04 21:13
Duplicate of #183

**Closed by borela** 2018-11-04 21:13 UTC
